### PR TITLE
replace .m.js with .mjs to be working in Node ESM

### PR DESCRIPTION
**Pull request by v1rtl**
Node.js requires either `.mjs` extension or `"type": "module"` + `.cjs` for CommonJS to work.

Here I've chosen the easiest way, changing `.m.js` to `.mjs` so it works.

It also works in browser (if it's even needed lol)

I tried to build and import sosse and it worked without crashes

### CODE REVIEW

**Comment by katywings** [comment]
@talentlessguy Thank you a lot for this pr and your investigation!

---

I just asked about this in the microbundle chat and got informed about some really annoying history: It looks like many different projects switched from *.js to *.mjs and had to revert to "*.js" because of other bundler/webpack issues :see_no_evil: ...

A couple examples:
- developit/microbundle@8cc0d7b3374c5dcaa745ea37b21b5ee7f975c882
- https://github.com/developit/microbundle/issues/426#issuecomment-504621384
- https://github.com/developit/microbundle/issues/426#issuecomment-504762376
- https://github.com/apollographql/react-apollo/issues/1737#issuecomment-373053005

---

Normally I would say "lets wait for the others / webpack to iron this out". But I think in this case lets go for it, since webpack really isn't a clear "platform" for sosse :D - but i have to give you a little "warning" notice: if mjs results in other yet unknown but major problems, I will have to revert this again ;).

**Comment by v1rtl** [comment]
@katywings oh, this is unfortunate

is there a better solution?

for now maybe let's keep it like that until bad things happen (if they happen)

**Comment by katywings** [comment]
> for now maybe let's keep it like that until bad things happen (if they happen)

yeah :)

> is there a better solution?

Fixing webpack? :P

---

But thank you again for your work :partying_face: !

**Comment by v1rtl** [comment]
@katywings could you please publish the patch version so I could use it :)?

**Comment by katywings** [comment]
@talentlessguy v0.6.0 is out with your change, and a little new feature of mine ;)

**Comment by v1rtl** [comment]
@katywings yay thanks

**Pull request merged**
